// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSGL6xGR2-Iber0reRs65KQsS_foPR6I8',
    appId: '1:607150132370:web:d23cdcdd649cea6c312a4b',
    messagingSenderId: '607150132370',
    projectId: 'logintask-dcfa8',
    authDomain: 'logintask-dcfa8.firebaseapp.com',
    storageBucket: 'logintask-dcfa8.appspot.com',
    measurementId: 'G-0W6JG5VFTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmXOstiNb9Cr0PYUALEgqvaevhcTRenic',
    appId: '1:607150132370:android:0f7e1df94c2e176c312a4b',
    messagingSenderId: '607150132370',
    projectId: 'logintask-dcfa8',
    storageBucket: 'logintask-dcfa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF_2yAgXBhRAevSxRRSoJubKJfzD1wUmo',
    appId: '1:607150132370:ios:324ac167319ffb9a312a4b',
    messagingSenderId: '607150132370',
    projectId: 'logintask-dcfa8',
    storageBucket: 'logintask-dcfa8.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF_2yAgXBhRAevSxRRSoJubKJfzD1wUmo',
    appId: '1:607150132370:ios:324ac167319ffb9a312a4b',
    messagingSenderId: '607150132370',
    projectId: 'logintask-dcfa8',
    storageBucket: 'logintask-dcfa8.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSGL6xGR2-Iber0reRs65KQsS_foPR6I8',
    appId: '1:607150132370:web:745976691b7d1cc9312a4b',
    messagingSenderId: '607150132370',
    projectId: 'logintask-dcfa8',
    authDomain: 'logintask-dcfa8.firebaseapp.com',
    storageBucket: 'logintask-dcfa8.appspot.com',
    measurementId: 'G-80WN2K7172',
  );
}
